# action.yml
name: 'PyWash your life'
description: 'Time to clean your code'
inputs:
  who-to-greet: 
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
branding:
  icon: 'shield'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
